# Generated by Django 4.1.5 on 2023-01-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tree_inheritance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='inheritance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.tree'),
        ),
    ]
