# Generated by Django 4.1.5 on 2023-01-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_treeobject_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
