# Generated by Django 4.1.5 on 2023-01-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_typemenu_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typemenu'),
        ),
    ]
