# Generated by Django 4.1.5 on 2023-01-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_menu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='typemenu',
            name='sys_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='typemenu',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
